# Generated by Django 3.2.7 on 2021-10-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='hit',
        ),
    ]
